version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - redis-network

networks:
  redis-network:
    driver: bridge

volumes:
  redis-data:
    driver: local